# Site settings
title1: "WinoBias "
title2: "Wino-grad schema dataset for detecting gender bias in coreference resolution systems."
email:  jyzhao@cs.ucla.edu
#description: "Seminar: Current Topics in Artificial Intelligence: Machine Learning in Natural Language Processing"
baseurl: "/corefBias"
url: "http://uclanlp.github.io/corefBias"
#twitter_username: jekyllrb
#github_username:  jekyll

# Build settings
markdown: kramdown
permalink: pretty

